-- the password hash is generated by BCrypt Calculator Generator(https://www.dailycred.com/article/bcrypt-calculator)

INSERT INTO user (id, username, password, firstname, lastname) VALUES (1, 'manager', '$2a$06$h6qKrHQAg03QjBMwh01EbebKcK.l7TwzLu8A4/mfykf9XIZd40u26', 'Cool', 'Manager');

INSERT INTO authority (id, name) VALUES (1, 'ROLE_USER');
INSERT INTO authority (id, name) VALUES (2, 'ROLE_ADMIN');

INSERT INTO user_authority (user_id, authority_id) VALUES (1, 1);
INSERT INTO user_authority (user_id, authority_id) VALUES (1, 2);
